apiVersion: v1
kind: Namespace
metadata:
  name: wordpress  # Namespace para los recursos de WordPress (Deployment, Service, PVCs, etc.)

---
apiVersion: v1
kind: Namespace
metadata:
  name: databases  # Namespace para bases de datos (MariaDB, Redis)

---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring  # Namespace para herramientas de monitoreo (Prometheus, Grafana, Loki)
