# ============================================================
# Secret para MariaDB en el namespace 'databases'
# Usado por los Pods de MariaDB
# ============================================================
apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secret
  namespace: databases
type: Opaque
data:
  # echo -n "RootDB#2024!" | base64  →  Um9vdERCIzIwMjQh
  # echo -n "WpUser#2024!" | base64  →  V3BVc2VyIzIwMjQh
  mariadb-root-password: Um9vdERCIzIwMjQh  # Solo usada por MariaDB internamente
  mariadb-user-password: V3BVc2VyIzIwMjQh  # Usada por WordPress para conectarse

---
# ============================================================
# Copia del Secret en el namespace 'wordpress'
# Necesaria porque los Secrets son namespace-scoped y WordPress
# necesita la contraseña de BD desde su propio namespace.
# IMPORTANTE: Mantener ambos sincronizados si cambias las contraseñas.
# En producción usar External Secrets Operator para sincronización automática.
# ============================================================
apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secret
  namespace: wordpress
type: Opaque
data:
  mariadb-user-password: V3BVc2VyIzIwMjQh  # Debe ser idéntico al de namespace 'databases'

---
# ============================================================
# Secret para Redis en el namespace 'databases'
# Usado por el Pod de Redis para arrancar con autenticación
# ============================================================
apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
  namespace: databases
type: Opaque
data:
  # echo -n "Redis#2024!" | base64  →  UmVkaXMjMjAyNCE=
  redis-password: UmVkaXMjMjAyNCE=

---
# ============================================================
# Copia del Secret de Redis en el namespace 'wordpress'
# WordPress necesita autenticarse con Redis para el caché
# ============================================================
apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
  namespace: wordpress
type: Opaque
data:
  redis-password: UmVkaXMjMjAyNCE=  # Debe ser idéntico al de namespace 'databases'
