apiVersion: v1               # Versió de l'API de Kubernetes per a objectes bàsics
kind: Secret                  # Tipus de recurs: Secret per emmagatzemar dades sensibles
metadata:
  name: mariadb-secret        # Nom del Secret que farem servir de referència als altres YAMLs
  namespace: wordpress-ha     # Namespace on s'ubica; només els Pods d'aquí el podran llegir
type: Opaque                  # Tipus de secret estàndard per a dades genèriques (clau/valor)
data:                         # Secció on van les dades reals
  # ATENCIÓ: Els valors següents han de ser el resultat de: echo -n "contrasenya" | base64
  mariadb-root-password: YWx1bW5lMTIz  # Contrasenya del superusuari 'root' en Base64
  mariadb-user-password: YWx1bW5lMTIz  # Contrasenya de l'usuari 'wordpress' en Base64
