apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingress-nginx-controller
  namespace: ingress-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ingress-nginx
  template:
    metadata:
      labels:
        app: ingress-nginx
    spec:
      containers:
        - name: ingress-nginx-controller
          image: quay.io/kubernetes-ingress-controller/nginx-ingress-controller:latest
          ports:
            - containerPort: 80
            - containerPort: 443
          env:
            - name: CONTROLLER_SERVICE
              value: ingress-nginx-controller
---
apiVersion: v1
kind: Service
metadata:
  name: ingress-nginx-controller
  namespace: ingress-nginx
spec:
  ports:
    - name: http    # Nombre del puerto HTTP
      port: 80
      targetPort: 80
    - name: https   # Nombre del puerto HTTPS
      port: 443
      targetPort: 443
  selector:
    app: ingress-nginx
