{
 "title": "Kubernetes Dashboard",
 "description": "K8S HA Minikube Optimized v4 - WordPress HA Monitoring (cAdvisor compatible, no container_spec_* metrics)",
 "tags": [
  "Prometheus",
  "Kubernetes"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "Node",
    "label": "Node",
    "query": {
     "query": "label_values(kube_node_info, node)"
    }
   },
   {
    "name": "NameSpace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_namespace_created, namespace)"
    }
   },
   {
    "name": "Container",
    "label": "Container",
    "query": {
     "query": "label_values(kube_pod_container_info{namespace=~\"$NameSpace\"}, container)"
    }
   },
   {
    "name": "Pod",
    "label": "Pod",
    "query": {
     "query": "label_values(kube_pod_container_info{namespace=~\"$NameSpace\",container=~\"$Container\"}, pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Node Resource Overview：Selected Nodes:【$Node】",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Node Memory Ratio",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{kubernetes_io_hostname=~\"$Node\"}) / sum(kube_node_status_allocatable{resource=\"memory\", unit=\"byte\", kubernetes_io_hostname=~\"$Node\"})",
     "legendFormat": "Memory Utilization"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\", unit=\"byte\",kubernetes_io_hostname=~\"$Node\"}) / sum(kube_node_status_allocatable{resource=\"memory\", unit=\"byte\", kubernetes_io_hostname=~\"$Node\"})",
     "legendFormat": "Memory Request Rate"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"memory\", unit=\"byte\",kubernetes_io_hostname=~\"$Node\"}) / sum(kube_node_status_allocatable{resource=\"memory\", unit=\"byte\", kubernetes_io_hostname=~\"$Node\"})",
     "legendFormat": "Memory Limit Rate"
    }
   ]
  },
  {
   "title": "Node CPU Ratio",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum (irate(container_cpu_usage_seconds_total{kubernetes_io_hostname=~\"$Node\"}[2m])) / sum(kube_node_status_allocatable{resource=\"cpu\", unit=\"core\", kubernetes_io_hostname=~\"$Node\"})",
     "legendFormat": "CPU Utilization Rate"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\", unit=\"core\",kubernetes_io_hostname=~\"$Node\"}) / sum(kube_node_status_allocatable{resource=\"cpu\", unit=\"core\", kubernetes_io_hostname=~\"$Node\"})",
     "legendFormat": "CPU Request Rate"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"cpu\", unit=\"core\",kubernetes_io_hostname=~\"$Node\"}) / sum(kube_node_status_allocatable{resource=\"cpu\", unit=\"core\", kubernetes_io_hostname=~\"$Node\"})",
     "legendFormat": "CPU Limit Rate"
    }
   ]
  },
  {
   "title": "Nodes with Pod",
   "type": "bargauge",
   "description": "Number of cluster nodes，Nodes POD Number of，NodesPODUpper Limit",
   "gridPos": { "h": 4, "w": 3, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "count(kube_node_info{})", "legendFormat": "Number of nodes" },
    {
     "expr": "count(kube_pod_info{created_by_kind!~\"<none>|Job\",kubernetes_io_hostname=~\"$Node\"})",
     "legendFormat": "Pod Number of nodes"
    },
    {
     "expr": "sum(kube_node_status_allocatable{resource=\"pods\", unit=\"integer\",kubernetes_io_hostname=~\"$Node\"})",
     "legendFormat": "Upper limit Pod"
    }
   ]
  },
  {
   "title": "Namespace Resource Statistics",
   "type": "table",
   "gridPos": { "h": 8, "w": 5, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count(kube_pod_info{kubernetes_io_hostname=~\"$Node\"}) by (namespace)"
    },
    {
     "expr": "count(kube_service_info{}) by(namespace)"
    },
    {
     "expr": "count by (namespace)({__name__=~\"kube_deployment_metadata_generation|kube_daemonset_metadata_generation|kube_statefulset_metadata_generation\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "count(kube_configmap_info{}) by(namespace)",
     "legendFormat": "configmap"
    },
    {
     "expr": "count(kube_secret_info{}) by(namespace)",
     "legendFormat": "secret"
    }
   ]
  },
  {
   "title": "$NameSpace：Network Overview（Associable nodes and namespaces）",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "expr": "sum (irate(container_network_receive_bytes_total{kubernetes_io_hostname=~\"$Node\",namespace=~\"$NameSpace\"}[2m]))*8",
     "legendFormat": "Receive"
    },
    {
     "expr": "sum (irate(container_network_transmit_bytes_total{kubernetes_io_hostname=~\"$Node\",namespace=~\"$NameSpace\"}[2m]))*8",
     "legendFormat": "Send"
    }
   ]
  },
  {
   "title": "Node Memory Information",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable{resource=\"memory\", unit=\"byte\", kubernetes_io_hostname=~\"$Node\"})",
     "legendFormat": "Total Memory"
    },
    {
     "expr": "sum (container_memory_working_set_bytes{kubernetes_io_hostname=~\"$Node\"})",
     "legendFormat": "Usage"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\", unit=\"byte\",kubernetes_io_hostname=~\"$Node\"})",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"memory\", unit=\"byte\",kubernetes_io_hostname=~\"$Node\"})",
     "legendFormat": "Limits"
    }
   ]
  },
  {
   "title": "Node CPU Number of cores",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable{resource=\"cpu\", unit=\"core\", kubernetes_io_hostname=~\"$Node\"})",
     "legendFormat": "Total Cores"
    },
    {
     "expr": "sum (irate(container_cpu_usage_seconds_total{id=\"/\",kubernetes_io_hostname=~\"$Node\"}[2m]))",
     "legendFormat": "Usage"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\", unit=\"core\",kubernetes_io_hostname=~\"$Node\"})",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"cpu\", unit=\"core\",kubernetes_io_hostname=~\"$Node\"})",
     "legendFormat": "Limit"
    }
   ]
  },
  {
   "title": "Node Storage Information",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 3, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum (container_fs_usage_bytes{device=~\"^/dev/.*$\",id=\"/\",kubernetes_io_hostname=~\"$Node\"}) / sum (container_fs_limit_bytes{device=~\"^/dev/.*$\",id=\"/\",kubernetes_io_hostname=~\"$Node\"})",
     "legendFormat": "Utilization Rate"
    },
    {
     "expr": "sum (container_fs_usage_bytes{device=~\"^/dev/.*$\",id=\"/\",kubernetes_io_hostname=~\"$Node\"})",
     "legendFormat": "Usage"
    },
    {
     "expr": "sum (container_fs_limit_bytes{device=~\"^/dev/.*$\",id=\"/\",kubernetes_io_hostname=~\"$Node\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 9 },
   "repeat": "origin_prometheus",
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count({__name__=~\"kube_deployment_metadata_generation|kube_daemonset_metadata_generation|kube_statefulset_metadata_generation\"})",
     "legendFormat": "Workload"
    },
    { "expr": "count(kube_pod_info{})", "legendFormat": "Total Pod" },
    {
     "expr": "count by(key,origin_prometheus)(kube_node_spec_taint{key=~\"node.kubernetes.io.*\"})",
     "legendFormat": "{{key}}"
    },
    {
     "expr": "count by(origin_prometheus)(kube_node_info{})",
     "legendFormat": "Total Nodes"
    },
    {
     "expr": "count by(origin_prometheus)(kube_node_info{}) - count by(origin_prometheus)(kube_node_spec_taint{key!~\"node.kubernetes.io.*\"})",
     "legendFormat": "Normal Node"
    },
    {
     "expr": "count by(key,origin_prometheus)(kube_node_spec_taint{key!~\"node.kubernetes.io.*\"})",
     "legendFormat": "{{key}}"
    }
   ]
  },
  {
   "title": "Memory Usage【$Node】",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable{resource=\"memory\", unit=\"byte\", kubernetes_io_hostname=~\"$Node\"})",
     "legendFormat": "Total Memory"
    },
    {
     "expr": "sum (container_memory_working_set_bytes{kubernetes_io_hostname=~\"$Node\"})",
     "legendFormat": "Usage"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\", unit=\"byte\",kubernetes_io_hostname=~\"$Node\"})",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"memory\", unit=\"byte\",kubernetes_io_hostname=~\"$Node\"})",
     "legendFormat": "Limit"
    }
   ]
  },
  {
   "title": "CPU Used Cores【$Node】",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable{resource=\"cpu\", unit=\"core\", kubernetes_io_hostname=~\"$Node\"})",
     "legendFormat": "Total Cores"
    },
    {
     "expr": "sum (irate(container_cpu_usage_seconds_total{id=\"/\",kubernetes_io_hostname=~\"$Node\"}[2m]))",
     "legendFormat": "Usage"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\", unit=\"core\",kubernetes_io_hostname=~\"$Node\"})",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"cpu\", unit=\"core\",kubernetes_io_hostname=~\"$Node\"})",
     "legendFormat": "Limit"
    }
   ]
  },
  {
   "title": "Pod Number and nodes【$Node】",
   "type": "timeseries",
   "description": "Number of Cluster Nodes，Nodes POD Number of，Nodes POD Upper Limit",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "count(kube_node_info{})", "legendFormat": "Number of nodes" },
    {
     "expr": "count(kube_pod_info{created_by_kind!~\"<none>|Job\",kubernetes_io_hostname=~\"$Node\"})",
     "legendFormat": "Pod Number"
    },
    {
     "expr": "sum(kube_node_status_allocatable{resource=\"pods\", unit=\"integer\",kubernetes_io_hostname=~\"$Node\"})",
     "legendFormat": "Upper Limit Pod"
    }
   ]
  },
  {
   "title": "$Node：Nodes CPU Breakdown",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum (irate(container_cpu_usage_seconds_total{kubernetes_io_hostname=~\"$Node\"}[2m]))by (kubernetes_io_hostname) / scalar(sum(kube_node_status_allocatable{resource=\"cpu\",unit=\"core\"}))*100",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "$Node：Node Memory Breakdown",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{kubernetes_io_hostname=~\"$Node\"})by (kubernetes_io_hostname) / scalar(sum(kube_node_status_allocatable{resource=\"memory\",unit=\"byte\"}))*100",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "$Node：Node Network Overview",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "expr": "sum (irate(container_network_receive_bytes_total{kubernetes_io_hostname=~\"$Node\"}[2m]))by (kubernetes_io_hostname) *8",
     "legendFormat": "Inflow:{{node}}"
    },
    {
     "expr": "sum (irate(container_network_transmit_bytes_total{kubernetes_io_hostname=~\"$Node\"}[2m]))by (kubernetes_io_hostname) *8",
     "legendFormat": "Outflows:{{node}}"
    }
   ]
  },
  {
   "title": "$Node：Node Information Detail",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "count(kube_pod_info{created_by_kind!~\"<none>|Job\",kubernetes_io_hostname=~\"$Node\"}) by (kubernetes_io_hostname)",
     "legendFormat": "pod Number"
    },
    {
     "expr": "kube_node_status_condition{status=\"true\",kubernetes_io_hostname=~\"$Node\"}  == 1",
     "legendFormat": "Status"
    },
    {
     "expr": "sum (irate(container_cpu_usage_seconds_total{kubernetes_io_hostname=~\"$Node\"}[2m])) by (kubernetes_io_hostname)"
    },
    {
     "expr": "kube_node_status_allocatable{resource=\"cpu\", unit=\"core\", kubernetes_io_hostname=~\"$Node\"} - 0"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\", unit=\"core\",kubernetes_io_hostname=~\"$Node\"}) by (kubernetes_io_hostname)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"cpu\", unit=\"core\",kubernetes_io_hostname=~\"$Node\"}) by (kubernetes_io_hostname)"
    },
    {
     "expr": "sum (container_memory_working_set_bytes{kubernetes_io_hostname=~\"$Node\"}) by (kubernetes_io_hostname)"
    },
    {
     "expr": "sum(kube_node_status_allocatable{resource=\"memory\", unit=\"byte\", kubernetes_io_hostname=~\"$Node\"}) by (kubernetes_io_hostname) - 0"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\", unit=\"byte\",kubernetes_io_hostname=~\"$Node\"}) by (kubernetes_io_hostname)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"memory\", unit=\"byte\",kubernetes_io_hostname=~\"$Node\"}) by (kubernetes_io_hostname)"
    },
    {
     "expr": "sum (container_fs_usage_bytes{device=~\"^/dev/.*$\",id=\"/\",kubernetes_io_hostname=~\"$Node\"}) by (kubernetes_io_hostname)"
    },
    {
     "expr": "sum (container_fs_limit_bytes{device=~\"^/dev/.*$\",id=\"/\",kubernetes_io_hostname=~\"$Node\"}) by (kubernetes_io_hostname)"
    },
    {
     "expr": "sum (container_memory_working_set_bytes{kubernetes_io_hostname=~\"$Node\"})by (kubernetes_io_hostname) / scalar(sum(kube_node_status_allocatable{resource=\"memory\",unit=\"byte\"}))",
     "legendFormat": "Memory Usage%"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\", unit=\"byte\",kubernetes_io_hostname=~\"$Node\"})by (kubernetes_io_hostname) / sum(kube_node_status_allocatable{resource=\"memory\", unit=\"byte\", kubernetes_io_hostname=~\"$Node\"})by (kubernetes_io_hostname)",
     "legendFormat": "Memory Requests%"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"memory\", unit=\"byte\",kubernetes_io_hostname=~\"$Node\"})by (kubernetes_io_hostname) / sum(kube_node_status_allocatable{resource=\"memory\", unit=\"byte\", kubernetes_io_hostname=~\"$Node\"})by (kubernetes_io_hostname)",
     "legendFormat": "Memory Limit%"
    },
    {
     "expr": "sum (irate(container_cpu_usage_seconds_total{kubernetes_io_hostname=~\"$Node\"}[2m]))by (kubernetes_io_hostname) / scalar(sum(kube_node_status_allocatable{resource=\"cpu\",unit=\"core\"}))",
     "legendFormat": "CPU Usage%"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\", unit=\"core\",kubernetes_io_hostname=~\"$Node\"})by (kubernetes_io_hostname) / sum(kube_node_status_allocatable{resource=\"cpu\", unit=\"core\", kubernetes_io_hostname=~\"$Node\"})by (kubernetes_io_hostname)",
     "legendFormat": "CPU Requests%"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"cpu\", unit=\"core\",kubernetes_io_hostname=~\"$Node\"})by (kubernetes_io_hostname) / sum(kube_node_status_allocatable{resource=\"cpu\", unit=\"core\", kubernetes_io_hostname=~\"$Node\"})by (kubernetes_io_hostname)",
     "legendFormat": "Memory Limit%"
    },
    {
     "expr": "sum (container_fs_usage_bytes{device=~\"^/dev/.*$\",id=\"/\",kubernetes_io_hostname=~\"$Node\"})by (kubernetes_io_hostname) / sum (container_fs_limit_bytes{device=~\"^/dev/.*$\",id=\"/\",kubernetes_io_hostname=~\"$Node\"})by (kubernetes_io_hostname)",
     "legendFormat": "Disk Usage%"
    },
    {
     "expr": "sum(kube_node_status_allocatable{resource=\"pods\", unit=\"integer\",kubernetes_io_hostname=~\"$Node\"})by (kubernetes_io_hostname)",
     "legendFormat": "PodCaps"
    }
   ]
  },
  {
   "title": "PVC Storage Usage",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_fs_usage_bytes{}) by (namespace)",
     "legendFormat": "{{namespace}}"
    },
    {
     "expr": "sum(container_fs_limit_bytes{}) by (namespace)",
     "legendFormat": "{{namespace}}"
    },
    {
     "expr": "sum(container_fs_usage_bytes{}) by (namespace) / sum(container_fs_limit_bytes{}) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Namespaces CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 6, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{}[2m])) by (namespace)",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "Namespaces Memory Usage (WSS)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{}) by (namespace)",
     "legendFormat": "{{namespace} {{ pod }}"
    }
   ]
  },
  {
   "title": "Pod Resource Overview：SelectedPod:【$Pod】",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 }
  },
  {
   "title": "$Node：Pod Resource Detail(Associable Nodes)",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{id=~\"/kubepods.*slice$\",namespace=~\"$NameSpace\",pod=~\"$Pod\"}[2m])) by (pod, namespace) / scalar(sum(kube_node_status_allocatable{resource=\"cpu\",unit=\"core\"})) * 100"
    },
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{pod=~\"$Pod\",kubernetes_io_hostname=~\"$Node\",namespace=~\"$NameSpace\"}[2m])) by (container, pod,namespace)",
     "legendFormat": "CPUKernel Usage"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\", unit=\"core\",pod=~\"$Pod\",container =~\"$Container\",kubernetes_io_hostname=~\"$Node\",namespace=~\"$NameSpace\"}) by (container,pod,namespace)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"cpu\", unit=\"core\",pod=~\"$Pod\",container =~\"$Container\",kubernetes_io_hostname=~\"$Node\",namespace=~\"$NameSpace\"}) by (container,pod,namespace)"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{id=~\"/kubepods.*slice$\",namespace=~\"$NameSpace\",pod=~\"$Pod\"}) by (pod, namespace)",
     "legendFormat": "wss%"
    },
    {
     "expr": "sum (container_memory_working_set_bytes{pod=~\"$Pod\",kubernetes_io_hostname=~\"$Node\",namespace=~\"$NameSpace\"}) by (container, pod,namespace)",
     "legendFormat": "wss"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{id=~\"/kubepods.*slice$\",namespace=~\"$NameSpace\",pod=~\"$Pod\"}) by (pod, namespace)",
     "legendFormat": "rss%"
    },
    {
     "expr": "sum (container_memory_working_set_bytes{pod=~\"$Pod\",kubernetes_io_hostname=~\"$Node\",namespace=~\"$NameSpace\"}) by (container, pod,namespace)",
     "legendFormat": "rss"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\", unit=\"byte\",pod=~\"$Pod\",container =~\"$Container\",kubernetes_io_hostname=~\"$Node\",namespace=~\"$NameSpace\"}) by (container,pod,namespace)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"memory\", unit=\"byte\",pod=~\"$Pod\",container =~\"$Container\",kubernetes_io_hostname=~\"$Node\",namespace=~\"$NameSpace\"}) by (container,pod,namespace)"
    },
    {
     "expr": "sum(container_fs_usage_bytes{pod=~\"$Pod\",kubernetes_io_hostname=~\"$Node\",namespace=~\"$NameSpace\"}) by (container,pod,namespace)"
    },
    {
     "expr": "kube_pod_container_status_restarts_total{pod=~\"$Pod\",container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"} * on (pod) group_left(node) kube_pod_info{pod=~\"$Pod\",kubernetes_io_hostname=~\"$Node\",namespace=~\"$NameSpace\"}"
    },
    {
     "expr": "time() - kube_pod_created{pod=~\"$Pod\",namespace=~\"$NameSpace\"} * on(pod) group_right kube_pod_container_info{pod=~\"$Pod\",namespace=~\"$NameSpace\",container =~\"$Container\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(container_fs_limit_bytes{pod=~\"$Pod\",kubernetes_io_hostname=~\"$Node\",namespace=~\"$NameSpace\"}) by (container,pod,namespace)"
    },
    {
     "expr": "sum(sum(irate(container_network_receive_bytes_total{pod=~\"$Pod\",kubernetes_io_hostname=~\"$Node\",namespace=~\"$NameSpace\"}[2m])) by (pod)* on(pod) group_right kube_pod_container_info{pod=~\"$Pod\",namespace=~\"$NameSpace\",container =~\"$Container\"}) by(pod) *8",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(sum(irate(container_network_transmit_bytes_total{pod=~\"$Pod\",kubernetes_io_hostname=~\"$Node\",namespace=~\"$NameSpace\"}[2m])) by (pod)* on(pod) group_right kube_pod_container_info{pod=~\"$Pod\",namespace=~\"$NameSpace\",container =~\"$Container\"}) by(pod) *8",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod Containers CPU Core Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max(irate(container_cpu_usage_seconds_total{pod=~\"$Pod\",kubernetes_io_hostname=~\"$Node\",namespace=~\"$NameSpace\"}[2m])) by (container, pod,namespace)",
     "legendFormat": "CPU Usage：{{ pod }}"
    },
    {
     "expr": "max(max(kube_pod_container_resource_limits{resource=\"cpu\", unit=\"core\",pod=~\"$Pod\",container =~\"$Container\",kubernetes_io_hostname=~\"$Node\",namespace=~\"$NameSpace\"}) by (container,pod,namespace)) by(container)",
     "legendFormat": "Pod CPU Limitations：{{ container}}"
    }
   ]
  },
  {
   "title": "Pod Container Memory Usage (Associatable Nodes)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max(container_memory_working_set_bytes{pod=~\"$Pod\",namespace=~\"$NameSpace\"}) by (container, pod)",
     "legendFormat": "WSS {{pod}} / {{container}}"
    },
    {
     "expr": "max(kube_pod_container_resource_limits{resource=\"memory\",unit=\"byte\",pod=~\"$Pod\",container=~\"$Container\",namespace=~\"$NameSpace\"}) by (container, pod)",
     "legendFormat": "Limit {{pod}} / {{container}}"
    }
   ]
  },
  {
   "title": "Pod Containers RSS Memory Usage (Associable Nodes)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max (container_memory_working_set_bytes{pod=~\"$Pod\",kubernetes_io_hostname=~\"$Node\",namespace=~\"$NameSpace\"}) by (container, pod,namespace)",
     "legendFormat": "RSS：{{ pod }}"
    }
   ]
  },
  {
   "title": "Pod Containers WSS Memory Usage (Associable Nodes)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max (container_memory_working_set_bytes{pod=~\"$Pod\",kubernetes_io_hostname=~\"$Node\",namespace=~\"$NameSpace\"}) by (container, pod,namespace)",
     "legendFormat": "WSS：{{ pod }}"
    },
    {
     "expr": "max(max(kube_pod_container_resource_limits{resource=\"memory\", unit=\"byte\",pod=~\"$Pod\",container =~\"$Container\",kubernetes_io_hostname=~\"$Node\",namespace=~\"$NameSpace\"}) by (container,pod,namespace)) by(container)",
     "legendFormat": "PodMemory Limits：{{ container}}"
    }
   ]
  },
  {
   "title": "Microservices (Container Name) Resource Overview：Selected Microservices:【$Container】",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 }
  },
  {
   "title": "Microservices (Container Name) Resource Statistics",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{id=~\"/kubepods.*slice$\",namespace=~\"$NameSpace\",pod=~\"$Pod\"}[2m])) by (pod, namespace) / scalar(sum(kube_node_status_allocatable{resource=\"cpu\",unit=\"core\"})) * 100"
    },
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{namespace=~\"$NameSpace\"}[2m])) by (container)",
     "legendFormat": "Total Cores Used"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\", unit=\"core\",container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}) by (container)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"cpu\", unit=\"core\",container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}) by (container)"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{id=~\"/kubepods.*slice$\",namespace=~\"$NameSpace\",pod=~\"$Pod\"}) by (pod, namespace)"
    },
    {
     "expr": "sum (container_memory_working_set_bytes{namespace=~\"$NameSpace\"}) by (container)"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{id=~\"/kubepods.*slice$\",namespace=~\"$NameSpace\",pod=~\"$Pod\"}) by (pod, namespace)",
     "legendFormat": "Average Memory%(RSS)"
    },
    {
     "expr": "sum (container_memory_working_set_bytes{namespace=~\"$NameSpace\"}) by (container)",
     "legendFormat": "Total Memory Usage (RSS) "
    },
    {
     "expr": "sum by(container) (kube_pod_container_resource_requests{resource=\"memory\", unit=\"byte\",container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"})"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"memory\", unit=\"byte\",container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}) by (container)"
    },
    {
     "expr": "avg(container_fs_usage_bytes{namespace=~\"$NameSpace\"}) by (container)"
    },
    {
     "expr": "count(kube_pod_container_info{container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}) by(container,namespace)"
    },
    {
     "expr": "avg(container_fs_limit_bytes{namespace=~\"$NameSpace\"}) by (container)"
    }
   ]
  },
  {
   "title": "Microservices (Container Name) Average CPU Usage (Maximum100%)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{id=~\"/kubepods.*slice$\",namespace=~\"$NameSpace\",pod=~\"$Pod\"}[2m])) by (pod, namespace) / scalar(sum(kube_node_status_allocatable{resource=\"cpu\",unit=\"core\"})) * 100",
     "legendFormat": "{{ container}}"
    }
   ]
  },
  {
   "title": "Microservice (Container Name) Average Memory Utilization",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{id=~\"/kubepods.*slice$\",namespace=~\"$NameSpace\",pod=~\"$Pod\"}) by (pod, namespace)",
     "legendFormat": "WSS：{{ container }}"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{id=~\"/kubepods.*slice$\",namespace=~\"$NameSpace\",pod=~\"$Pod\"}) by (pod, namespace)",
     "legendFormat": "RSS：{{ container }}"
    }
   ]
  },
  {
   "title": "Microservice (Container Name) Network bandwidth per second (Associable Nodes)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "expr": "sum(sum(irate(container_network_receive_bytes_total{kubernetes_io_hostname=~\"$Node\",namespace=~\"$NameSpace\"}[2m])) by (pod)* on(pod) group_right kube_pod_container_info{namespace=~\"$NameSpace\",container =~\"$Container\"}) by(container) *8",
     "legendFormat": "Inflow:{{ container }}"
    },
    {
     "expr": "sum(sum(irate(container_network_transmit_bytes_total{kubernetes_io_hostname=~\"$Node\",namespace=~\"$NameSpace\"}[2m])) by (pod)* on(pod) group_right kube_pod_container_info{namespace=~\"$NameSpace\",container =~\"$Container\"}) by(container) *8",
     "legendFormat": "Outflow:{{ container }}"
    },
    {
     "expr": "sum (rate (container_network_receive_bytes_total{pod=~\"$Pod\",kubernetes_io_hostname=~\"$Node\",namespace=~\"$NameSpace\"}[2m])) by (pod)",
     "legendFormat": "-> {{ pod }}"
    },
    {
     "expr": "- sum (rate (container_network_transmit_bytes_total{pod=~\"$Pod\",kubernetes_io_hostname=~\"$Node\",namespace=~\"$NameSpace\"}[2m])) by (pod)",
     "legendFormat": "<- {{ pod }}"
    }
   ]
  },
  {
   "title": "Microservices (Container Name) Overall CPU Cores Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"cpu\", unit=\"core\",container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}) by (container)",
     "legendFormat": "CPU Limitations：{{ container}}"
    },
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{namespace=~\"$NameSpace\"}[2m])) by (container)",
     "legendFormat": "CPU Core Usage：{{ container}}"
    }
   ]
  },
  {
   "title": "Microservices (Container Name) Overall Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{namespace=~\"$NameSpace\"}) by (container)",
     "legendFormat": "WSS：{{ container }}"
    },
    {
     "expr": "max(container_memory_working_set_bytes{pod=~\"$Pod\",namespace=~\"$NameSpace\"}) by (container, pod)",
     "legendFormat": "Memory Limit：{{ container }}"
    },
    {
     "expr": "sum (container_memory_working_set_bytes{namespace=~\"$NameSpace\"}) by (container)",
     "legendFormat": "RSS：{{ container }}"
    }
   ]
  },
  {
   "title": "Microservice (Container Name) Pod Number",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count(kube_pod_container_info{container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}) by(container,namespace)",
     "legendFormat": "{{namespace}}：{{ container }}"
    }
   ]
  }
 ]
}